#!/bin/bash
if [ "${bistatic}" == "on" ]; then
  #openInIpython "${ADOREFOLDER}/lib/python/fun/subtrrefdem_bistatic.py"
  floatmult ${crd_out_file} 0.5
  mv ${crd_out_file}.floatmult0.5 ${crd_out_file}
fi
pp ${dorisProcess}  
doris ${outputFolder}/${dorisProcess}.drs

[ $? -eq 0 ] && echo "${dorisProcess}: SUCCESS"
