#!/bin/bash
if [ "${bistatic}" == "on" ]; then
openInIpython "${ADOREFOLDER}/lib/python/fun/subtrrefdem_bistatic.py"
  floatmult ${crd_out_dem} 0.5
  mv ${crd_out_dem}.floatmult0.5 ${crd_out_dem}
fi
pp ${dorisProcess}  
doris ${outputFolder}/${dorisProcess}.drs
[ $? -eq 0 ] && echo "${dorisProcess}: SUCCESS"
